sudo: required
services:
  - docker

before_install:
  - docker build -t frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-frontend"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-us-east-1-360367874658"
  bucket_path: "react-frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"